#include "swiatla.h"

#if 0
void swiatla()
{

    MyMessage msg_S_LIGHT_V_HOLA1(ID_S_LIGHT_HOLA1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLA2(ID_S_LIGHT_HOLA2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLA3(ID_S_LIGHT_HOLA3,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLB1(ID_S_LIGHT_HOLB1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLB2(ID_S_LIGHT_HOLB2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLB3(ID_S_LIGHT_HOLB3,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLB4(ID_S_LIGHT_HOLB4,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLB5(ID_S_LIGHT_HOLB5,V_LIGHT);
    MyMessage msg_S_LIGHT_V_HOLC1(ID_S_LIGHT_HOLC1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_PRAC1(ID_S_LIGHT_PRAC1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_PRAC2(ID_S_LIGHT_PRAC2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_POK1(ID_S_LIGHT_POK1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_POK2(ID_S_LIGHT_POK2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZ1(ID_S_LIGHT_LAZ1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZ2(ID_S_LIGHT_LAZ2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZP1(ID_S_LIGHT_LAZP1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZP2(ID_S_LIGHT_LAZP2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZP3(ID_S_LIGHT_LAZP3,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZP4(ID_S_LIGHT_LAZP4,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZW1(ID_S_LIGHT_LAZW1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZW2(ID_S_LIGHT_LAZW2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZL1(ID_S_LIGHT_LAZL1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_LAZL2(ID_S_LIGHT_LAZL2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SyP1(ID_S_LIGHT_SyP1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SYP2(ID_S_LIGHT_SYP2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_JAD1(ID_S_LIGHT_JAD1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_JAD2(ID_S_LIGHT_JAD2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_JAD3(ID_S_LIGHT_JAD3,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH1(ID_S_LIGHT_KUCH1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH2(ID_S_LIGHT_KUCH2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH3(ID_S_LIGHT_KUCH3,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH4(ID_S_LIGHT_KUCH4,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH5(ID_S_LIGHT_KUCH5,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH6(ID_S_LIGHT_KUCH6,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH7(ID_S_LIGHT_KUCH7,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH8(ID_S_LIGHT_KUCH8,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCH9(ID_S_LIGHT_KUCH9,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCHL1(ID_S_LIGHT_KUCHL1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCHL2(ID_S_LIGHT_KUCHL2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_KUCHS(ID_S_LIGHT_KUCHS,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SAL1(ID_S_LIGHT_SAL1,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SAL2(ID_S_LIGHT_SAL2,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SALL11(ID_S_LIGHT_SALL11,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SALL12(ID_S_LIGHT_SALL12,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SALL21(ID_S_LIGHT_SALL21,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SALL22(ID_S_LIGHT_SALL22,V_LIGHT);
    MyMessage msg_S_LIGHT_V_SYPW(ID_S_LIGHT_SYPW,V_LIGHT);

    msg_S_LIGHT_V_HOLA1.set(0);
    msg_S_LIGHT_V_HOLA2.set(0);
    msg_S_LIGHT_V_HOLA3.set(0);
    msg_S_LIGHT_V_HOLB1.set(0);
    msg_S_LIGHT_V_HOLB2.set(0);
    msg_S_LIGHT_V_HOLB3.set(0);
    msg_S_LIGHT_V_HOLB4.set(0);
    msg_S_LIGHT_V_HOLB5.set(0);
    msg_S_LIGHT_V_HOLC1.set(0);
    msg_S_LIGHT_V_PRAC1.set(0);
    msg_S_LIGHT_V_PRAC2.set(0);
    msg_S_LIGHT_V_POK1.set(0);
    msg_S_LIGHT_V_POK2.set(0);
    msg_S_LIGHT_V_LAZ1.set(0);
    msg_S_LIGHT_V_LAZ2.set(0);
    msg_S_LIGHT_V_LAZP1.set(0);
    msg_S_LIGHT_V_LAZP2.set(0);
    msg_S_LIGHT_V_LAZP3.set(0);
    msg_S_LIGHT_V_LAZP4.set(0);
    msg_S_LIGHT_V_LAZW1.set(0);
    msg_S_LIGHT_V_LAZW2.set(0);
    msg_S_LIGHT_V_LAZL1.set(0);
    msg_S_LIGHT_V_LAZL2.set(0);
    msg_S_LIGHT_V_SyP1.set(0);
    msg_S_LIGHT_V_SYP2.set(0);
    msg_S_LIGHT_V_JAD1.set(0);
    msg_S_LIGHT_V_JAD2.set(0);
    msg_S_LIGHT_V_JAD3.set(0);
    msg_S_LIGHT_V_KUCH1.set(0);
    msg_S_LIGHT_V_KUCH2.set(0);
    msg_S_LIGHT_V_KUCH3.set(0);
    msg_S_LIGHT_V_KUCH4.set(0);
    msg_S_LIGHT_V_KUCH5.set(0);
    msg_S_LIGHT_V_KUCH6.set(0);
    msg_S_LIGHT_V_KUCH7.set(0);
    msg_S_LIGHT_V_KUCH8.set(0);
    msg_S_LIGHT_V_KUCH9.set(0);
    msg_S_LIGHT_V_KUCHL1.set(0);
    msg_S_LIGHT_V_KUCHL2.set(0);
    msg_S_LIGHT_V_KUCHS.set(0);
    msg_S_LIGHT_V_SAL1.set(0);
    msg_S_LIGHT_V_SAL2.set(0);
    msg_S_LIGHT_V_SALL11.set(0);
    msg_S_LIGHT_V_SALL12.set(0);
    msg_S_LIGHT_V_SALL21.set(0);
    msg_S_LIGHT_V_SALL22.set(0);
    msg_S_LIGHT_V_SYPW.set(0);

    
}
void swiatla_presentation()
{
    present(ID_S_LIGHT_HOLA1,S_LIGHT,"Swiatlo hol A 1");
    present(ID_S_LIGHT_HOLA2,S_LIGHT,"Swiatlo hol A 2");
    present(ID_S_LIGHT_HOLA3,S_LIGHT,"Swiatlo hol A 3");
    present(ID_S_LIGHT_HOLB1,S_LIGHT,"Swiatlo hol B 1");
    present(ID_S_LIGHT_HOLB2,S_LIGHT,"Swiatlo hol B 2");
    present(ID_S_LIGHT_HOLB3,S_LIGHT,"Swiatlo hol B 3");
    present(ID_S_LIGHT_HOLB4,S_LIGHT,"Swiatlo hol B 4");
    present(ID_S_LIGHT_HOLB5,S_LIGHT,"Swiatlo hol B 5");
    present(ID_S_LIGHT_HOLC1,S_LIGHT,"Swiatlo hol C");
    present(ID_S_LIGHT_PRAC1,S_LIGHT,"Swiatlo pracownia 1");
    present(ID_S_LIGHT_PRAC2,S_LIGHT,"Swiatlo pracownia 2");
    present(ID_S_LIGHT_POK1,S_LIGHT,"Swiatlo pokoj 1");
    present(ID_S_LIGHT_POK2,S_LIGHT,"Swiatlo pokoj 2");
    present(ID_S_LIGHT_LAZP1,S_LIGHT,"Swiatlo lazienka prysznic 1");
    present(ID_S_LIGHT_LAZP2,S_LIGHT,"Swiatlo lazienka prysznic 2");
    present(ID_S_LIGHT_LAZP3,S_LIGHT,"Swiatlo lazienka prysznic 3");
    present(ID_S_LIGHT_LAZP4,S_LIGHT,"Swiatlo lazienka prysznic 4");
    present(ID_S_LIGHT_LAZW1,S_LIGHT,"Swiatlo lazienka wanna 1");
    present(ID_S_LIGHT_LAZW2,S_LIGHT,"Swiatlo lazienka wanna 2");
    present(ID_S_LIGHT_LAZL1,S_LIGHT,"Swiatlo lazienka lustro lewe");
    present(ID_S_LIGHT_LAZL2,S_LIGHT,"Swiatlo lazienka lustro prawe");
    present(ID_S_LIGHT_SyP1,S_LIGHT,"Swiatlo syplalnia 1");
    present(ID_S_LIGHT_SYP2,S_LIGHT,"Swiatlo syplalnia 2");
    present(ID_S_LIGHT_JAD1,S_LIGHT,"Swiatlo jadalnia 1");
    present(ID_S_LIGHT_JAD2,S_LIGHT,"Swiatlo jadalnia 2");
    present(ID_S_LIGHT_JAD3,S_LIGHT,"Swiatlo jadalnia 3");
    present(ID_S_LIGHT_KUCH1,S_LIGHT,"Swiatlo kuchnia 1");
    present(ID_S_LIGHT_KUCH2,S_LIGHT,"Swiatlo kuchnia 2");
    present(ID_S_LIGHT_KUCH3,S_LIGHT,"Swiatlo kuchnia 3");
    present(ID_S_LIGHT_KUCH4,S_LIGHT,"Swiatlo kuchnia 4");
    present(ID_S_LIGHT_KUCH5,S_LIGHT,"Swiatlo kuchnia 5");
    present(ID_S_LIGHT_KUCH6,S_LIGHT,"Swiatlo kuchnia 6");
    present(ID_S_LIGHT_KUCH7,S_LIGHT,"Swiatlo kuchnia 7");
    present(ID_S_LIGHT_KUCH8,S_LIGHT,"Swiatlo kuchnia 8");
    present(ID_S_LIGHT_KUCH9,S_LIGHT,"Swiatlo kuchnia 9");
    present(ID_S_LIGHT_KUCHL1,S_LIGHT,"Swiatlo kuchnia LED 1");
    present(ID_S_LIGHT_KUCHL2,S_LIGHT,"Swiatlo kuchnia LED 2");
    present(ID_S_LIGHT_KUCHS,S_LIGHT,"Swiatlo kuchnia szafki");
    present(ID_S_LIGHT_SAL1,S_LIGHT,"Swiatlo salon 1");
    present(ID_S_LIGHT_SAL2,S_LIGHT,"Swiatlo salon 2");
    present(ID_S_LIGHT_SALL11,S_LIGHT,"Swiatlo salon Led lewe 1");
    present(ID_S_LIGHT_SALL12,S_LIGHT,"Swiatlo salon Led lewe 2");
    present(ID_S_LIGHT_SALL21,S_LIGHT,"Swiatlo salon Led prawe 1");
    present(ID_S_LIGHT_SALL22,S_LIGHT,"Swiatlo salon Led prawe 2");
    present(ID_S_LIGHT_SYPW,S_LIGHT,"Swiatlo syplalnia nad lozkiem");
}
#endif
